/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 账号密码登录,返回用户资料 + token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 基于 Bearer 或 cookie 重签 token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册新用户 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录用户资料 */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/searchUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按微信号/手机号/用户名精确查找用户 */
        get: operations["searchUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/getFriendList/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 好友列表(id→备注 + id→资料 两张映射) */
        get: operations["getFriendList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/addFriend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 发起好友请求 */
        put: operations["addFriend"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/getFriendReqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的好友关系/请求(按对方 id 映射) */
        get: operations["getFriendReqs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/replyFriendReq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 回复好友请求(accepted/blocked) */
        put: operations["replyFriendReq"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/userConversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的会话视图列表 */
        get: operations["getUserConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话元信息(按会话 id 映射) */
        get: operations["getConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/lastMessages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 每会话最后一条消息(按会话 id 映射) */
        get: operations["getLastMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话全部消息(时间升序) */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/single": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 单文件上传(multipart),返回可访问 URL */
        post: operations["uploadSingle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OkEnvelope: {
            success: boolean;
            message?: string;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            message?: string;
        };
        User: {
            /**
             * Format: int64
             * @description 用户 id(即微信号)
             */
            id: number;
            username: string;
            email?: string | null;
            phone?: string | null;
            nickname?: string | null;
            avatar?: string | null;
            bio?: string | null;
            gender?: string | null;
            status?: string | null;
            /** Format: date-time */
            lastSeen?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        LoginData: components["schemas"]["User"] & {
            token: string;
        };
        /** @description 非文件消息时服务端下发空对象 {},故所有字段可选。 */
        FileInfo: {
            fileName?: string;
            /** Format: int64 */
            fileSize?: number;
            fileUrl?: string;
            fileType?: string;
            fileMd5?: string;
        };
        Message: {
            /** Format: int64 */
            id: number;
            conversationId: string;
            /** Format: int64 */
            senderId: number;
            /** Format: int64 */
            seq?: number | null;
            clientMsgId?: string | null;
            content: string;
            /** @description text | image | file | video | audio | system */
            type: string;
            status?: string | null;
            mentions?: number[];
            fileInfo?: components["schemas"]["FileInfo"];
            /** Format: date-time */
            timestamp?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        /** @description lastMessages 的末条消息预览(原生 SQL,仅含预览字段)。 */
        MessagePreview: {
            content?: string;
            type?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        UserConversation: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            conversationId: string;
            unreadCount?: number | null;
            isMuted?: boolean | null;
            isPinned?: boolean | null;
            /** Format: date-time */
            lastActivity?: string | null;
        };
        /** @description 会话元信息;按会话 id 映射下发,故 id 字段本身可省(键即 id)。 */
        Conversation: {
            id?: string;
            convType?: string | null;
            title?: string | null;
            avatar?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        FriendList: {
            friendId: {
                [key: string]: string | null;
            };
            friendInfo: {
                [key: string]: components["schemas"]["FriendInfo"];
            };
        };
        FriendInfo: {
            username: string;
            avatar?: string | null;
            gender?: string | null;
        };
        SearchUserResult: {
            exist?: boolean;
            isFriend?: boolean;
            friendInfo?: components["schemas"]["SearchedUser"];
        };
        SearchedUser: {
            /** Format: int64 */
            id: number;
            username: string;
            avatar?: string | null;
            gender?: string | null;
        };
        FriendRequest: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            friendId: number;
            /** @description sent | pending | accepted | blocked */
            status: string;
            remark?: string | null;
            username?: string | null;
            avatar?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        UploadResult: {
            url: string;
            originalName?: string;
            /** Format: int64 */
            size?: number;
            md5?: string;
        };
    };
    responses: {
        /** @description 错误信封 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    remember?: boolean;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        data?: components["schemas"]["LoginData"];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        data?: {
                            user?: components["schemas"]["User"];
                            token?: string;
                        };
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    email: string;
                    password: string;
                    phone?: string;
                    nickname?: string;
                    avatar?: string;
                    bio?: string;
                };
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    searchUser: {
        parameters: {
            query: {
                keyword: string;
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询结果(success=false 表示未命中/已是好友,data 仍带) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        data?: components["schemas"]["SearchUserResult"];
                    };
                };
            };
        };
    };
    getFriendList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 好友列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: components["schemas"]["FriendList"];
                    };
                };
            };
        };
    };
    addFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    userId: number;
                    /** Format: int64 */
                    friendId: number;
                };
            };
        };
        responses: {
            /** @description 已发起 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
        };
    };
    getFriendReqs: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 请求映射 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: {
                            [key: string]: components["schemas"]["FriendRequest"];
                        };
                    };
                };
            };
        };
    };
    replyFriendReq: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                    friendId: string;
                    /** @enum {string} */
                    status: "accepted" | "blocked";
                };
            };
        };
        responses: {
            /** @description 已回复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
        };
    };
    getUserConversations: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话视图数组 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: components["schemas"]["UserConversation"][];
                    };
                };
            };
        };
    };
    getConversations: {
        parameters: {
            query: {
                /** @description JSON 字符串数组 */
                userConversationIds: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话映射 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: {
                            [key: string]: components["schemas"]["Conversation"];
                        };
                    };
                };
            };
        };
    };
    getLastMessages: {
        parameters: {
            query: {
                /** @description JSON 字符串数组 */
                userConversationIds: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 末条消息映射(该接口走原生 SQL,仅取预览所需字段) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: {
                            [key: string]: components["schemas"]["MessagePreview"];
                        };
                    };
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query: {
                conversationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息数组 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: components["schemas"]["Message"][];
                    };
                };
            };
        };
    };
    uploadSingle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 上传结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data?: components["schemas"]["UploadResult"];
                    };
                };
            };
        };
    };
}
